### ISSUE TITLE
Time cosuming

### ISSUE THREAD

**Issue by arminkardovic** [spatie/async#100]
I have a project where I need to call 100 cURL calls and I am using this library.
first I create an example 

```
Route::post("data/testx", function (Illuminate\Http\Request $request) {
    $x = [1, 2, 3, 4, 5, 6];
    $start = microtime(true);
    $pool = Pool::create();
    foreach ($x as $y) {
        $pool[] = async(function () use ($y) {
            sleep($y);
            return ($y);
        })->then(function ($output) {
            print $output;
        })->catch(function ($exception) {
        });
    }
    await($pool);
    $time_elapsed_secs = microtime(true) - $start;
    print "---------------\n";
    print $time_elapsed_secs;
});
```

And this work correctly but when I use cURL times double
in data.zip you can find measurements of time how long cURL need to execute but full time is much more, I am expecting the longest response with maybe 2-3 seconds more but whole execution it goes up to 38 sec, you can see in JSON example 

[data.zip](https://github.com/spatie/async/files/3996531/data.zip)

  ```
$pool = Pool::create()->concurrency(60)->sleepTime(50000);
        foreach ($urls as $url) {
            $pool[] = async(function () use ($url) {
                $start = microtime(true);
                $curl = curl_init();
                curl_setopt_array($curl, array(
                    CURLOPT_URL => $url['url'],
                    CURLOPT_RETURNTRANSFER => true,
                    CURLOPT_ENCODING => "",
                    CURLOPT_MAXREDIRS => 3,
                    CURLOPT_TIMEOUT => 20,
                    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                    CURLOPT_CUSTOMREQUEST => "POST",
                    CURLOPT_POSTFIELDS => $url['postdata'],
                    CURLOPT_HTTPHEADER => array(),
                    CURLOPT_CONNECTTIMEOUT => 20,
                ));

                $response = curl_exec($curl);
                curl_close($curl);

                $time_elapsed_secs = microtime(true) - $start;
                return ["url" => $url['url'], "time" => $time_elapsed_secs];
            })->then(function ($output) use (&$data) {
                $data["key" . rand(999, 99999)] = $output;
            });
        }

```
In data.zip you can find results
Can you check and guide me on what I am doing wrong here?

**Comment by brendt** [comment]
Please check  if pcntl is supported on your system by using `phpinfo()` or `php -i | grep pcntl`

**Comment by arminkardovic** [comment]
Thanks for respond

pcntl support => enabled

**Comment by brendt** [comment]
What happens if you sleep in the child process for one second, and schedule 50 or so tasks?

**Comment by arminkardovic** [comment]
`use Spatie\Async\Pool;

$pool = Pool::create();
$counter = 0;
$start = microtime(true);

foreach (range(1, 50) as $i) {
    $pool[] = async(function () use ($counter) {
        sleep(0.3);
        return $counter + 1;
    })->then(function ($output) {
        print $output . "\n";
    });
}
await($pool);

$time_elapsed_secs = microtime(true) - $start;
print "---------------\n";
print $time_elapsed_secs;`

I am getting time 1.2505919933319 (1.2 seconds)

**Comment by brendt** [comment]
And why is this unexpected? The pool is configured to handle 20 concurrent processes by default, ending and creating new processes also add overhead. You can take a look at https://github.com/spatie/async/issues/97 for more information
