### ISSUE TITLE
Child process is not stop when we call method `markAsTimedOut` it continue work on background

### ISSUE THREAD

**Issue by alexspark21** [spatie/async#104]
I detect some problem when call command in linux terminal  `ps aux | grep ChildRuntime.php | wc -l` result it is number of running processes in system. 
My setting for Pool object concurrency - 5 and timeout - 2. 
When we check expression https://github.com/spatie/async/blob/9ddad44886aa63ddc94a6bb32f00f22aafda11d9/src/Pool.php#L133 
we call  `markAsTimedOut` but the child process is not stoped it continue work on background

**Comment by brendt** [comment]
The process should indeed be killed, which doesn't happen right now. Are you able to submit a PR?

**Comment by alexspark21** [comment]
@brendt https://github.com/spatie/async/pull/105

**Comment by alexspark21** [comment]
Hello @brendt pls could you check PR #105

**Comment by brendt** [comment]
Yes, I lost track of this one. Will check it next week!

**Comment by brendt** [comment]
Fix in 1.4.1: https://github.com/spatie/async/releases/tag/1.4.1
