### ISSUE TITLE
simple parallelism test is not working

### ISSUE THREAD

**Issue by samyomar** [spatie/async#114]
here is my code ... 

```
<?php
require "vendor/autoload.php";
use Spatie\Async\Pool;

$pool = Pool::create();

$start = microtime(true);
foreach (range(1, 20) as $i) {
    $pool[] = async(function () use ($i) {
        sleep(1);
        return $i;
    })->then(function (int $output) {
       echo $output . PHP_EOL;
    });
}
await($pool);

$time_elapsed_secs = microtime(true) - $start;
echo "Time take " . $time_elapsed_secs . PHP_EOL;

echo "All Done !" ;
```

the expected time to execute is 1 second if it will run in parallel, but it takes 20 seconds
this means that it's invoking the functions sequentially

**Comment by brendt** [comment]
Make sure ext-pcntl is installed and enabled, and you're running this is the command line, not on a web server.

Also please read https://github.com/spatie/async/issues/97 and report back if after that it's not clear.

**Comment by hannanstd** [comment]
hi
see this :

https://github.com/vuongxuongminh/laravel-async/issues/5

**Comment by D3faIt** [comment]
> Make sure ext-pcntl is installed and enabled, and you're running this is the command line, not on a web server.
> 
> Also please read #97 and report back if after that it's not clear.

Might be worth stating this in the README.md, I didn't realize it didn't work for web before I searched through the issues.
