### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by shihabmridha** [spatie/async#118]
PHP: 7.4 (Ubuntu)

In my Laravel app I did this:

```
class Campaign extends Model {
    private Pool $asyncPool;

    public function __construct(array $attributes = []) {
        parent::__construct($attributes);
        $this->asyncPool = Pool::create()->concurrency(5);
    }

    public function start() 
        try {
            $this->asyncPool->add(function () {
                // Log something to file
            })->then(function () {
                // Log something to file
            })->catch(function (\Exception $exception) {
                // I am not expecting to execute this block
            });
            
            $this->asyncPool->wait();
            // Do some other stuff
        } catch (\Exception $e) {
            // Log error
        }
    }
}
```

I get nothing in my log file and the program gets stuck here `$this->asyncPool->wait();`.
Getting no error!
`isSupported()` function returns `true`.

**Comment by brendt** [comment]
```
            })->catch(function (\Exception $exception) {
                // I am not expecting to execute this block
            });
```

The only thing I can think of is that an exception was thrown, if no log messages were written. Could you try to debug over there? Also make sure to read https://github.com/spatie/async/issues/97

**Comment by shihabmridha** [comment]
I did check the catch block. It didn't get executed. Let's assume an was thrown or whatever. Why did it get stuck `$this->asyncPool->wait();` here? Can you think of any case where `wait()` might get stuck?

Thank you

**Comment by brendt** [comment]
Wait will wait until all child processes are finished. You could write to a file within your child processes to debug what's going on. I think that's the best approach if nothing else works. It sounds like your child processes are never finishing.

**Comment by shihabmridha** [comment]
Probably something is wrong with my environment. In my local machine, I have created a docker container where I run the exact same code and it works as expected.
