### ISSUE TITLE
Cant install async

### ISSUE THREAD

**Issue by agusalex** [spatie/async#122]
Hi! im having trouble installing async
- I installed it on Mac like so

`brew install php composer;
cd /my_dir;`

- /my_dir/composer.json contents:

`{
    "require": {
        "spatie/async": "1.5.0"
    }
}`
`composer install`

- It installs ok

- Finally run the web server with this simple php file (/my_dir/myFile.php):

`php -a localhost:8080`
`<?php
use Spatie\Async\Pool;
$pool = Pool::create();
?>`

- And I get this:

`Fatal error: Uncaught Error: Class 'Pool' not found in /my_dir/myFile.php:2 Stack trace: #0 {main} thrown in ....
`
What am I missing ?

**Comment by junior-alves** [comment]
Do you need include composer autoload in the file.

**Comment by brendt** [comment]
You're missing composer's autoloader. You can do research on that in composer's documentation.
