### ISSUE TITLE
Cannot start async task

### ISSUE THREAD

**Issue by minhthien309** [spatie/async#127]
Hello everyone, I don't know why my code is not running async

    use Spatie\Async\Pool;

    $pool = Pool::create();
    $resultArray = [];
    $things = [1,2,3,4,5];

    foreach ($things as $thing) {
        $pool->add(function () use ($thing) {
            if($thing == 2){
                sleep(3);
            }
            return $thing;
        })->then(function ($output) use(&$resultArray) {
            return $resultArray[] = $output;
        })->catch(function (Throwable $exception) {
            // Handle exception
        });
    }

    $pool->wait();

I'm expected it is non blocking but result returned is blocking. Thank you!

**Comment by mrsnut** [comment]
It is running async, just blocks so the child processes which aren't done aren't accidently killed, read: https://github.com/spatie/async#behind-the-curtains

**Comment by AlexVanderbist** [comment]
Thanks @mrsnut  :)
