### ISSUE TITLE
How to work async ?

### ISSUE THREAD

**Issue by ph1823** [spatie/async#128]
Hi ! I see the #97 issue and i think this package correspond to me.

Here is my concern: I perform a task that creates ZIP archives but I don't want it to be blocking. Here is my first code:

```php
async(function () use ($minecraft) {
    $minecraft->saveMinecraft();
});
```

The one didn't work because I forgot the -> start at the end. Except that by adding this, it blocks my for loop.

So I tried the past with a Pool with:
```php
$pool = Pool::create();
```

but did work as well :(
So I allow myself to open an issue, to be sure how the async works. Is it supposed to be non-blocking or not?

Thank for your reply !

**Comment by mrsnut** [comment]
This library seems to be more for "alot of the same processes, at the same time". It's blocking to make sure child processes that aren't done yet are not prematurely killed: https://github.com/spatie/async#behind-the-curtains

**Comment by ph1823** [comment]
Alright fine, so for example in my for loop I can add whatever calls I want, and after the for loop run it with confidence?

I thought it wasn't blocking like in JS, as much for me.

Thank you for your reply
