### ISSUE TITLE
(question) Can this library execute code after the headers have been sent?

### ISSUE THREAD

**Issue by quiquelhappy** [spatie/async#130]
Hello,
I would like to implement this into my rest API. In order to provide fast responses, I would like to return a response before the pool has finished to execute. Will returning a response to the user kill the pool halfway? Or can it continue executing even after headers/response has been sent? If not, is there any library I can use?

Thanks in advance!

**Comment by AlexVanderbist** [comment]
I'd think you're safe to start writing headers to the response output while other tasks in the pool are still running. However, I don't think we've ever tested this... I'd suggest setting up a quick test script instead of taking my word for it ;) 

Good luck!
