### ISSUE TITLE
async() vs $pool->add()

### ISSUE THREAD

**Issue by allantatter** [spatie/async#131]
After I updated Composer from 1 to 2 in my application which also caused a bunch of other updates in my dependencies, a simple example does not work any more in my app:

```
            $pool = Pool::create();

            foreach ($xs as $i => $x) {
                $pool->add(function () {
                    //
                });
            }

            $pool->wait();
```

Tried to find out what exactly caused this simple example not to work any more but with no luck. Followed your error handling section in readme more than 10x :) I didn't get anywhere a better exception than a `ParallelError`.

When trying to re-create the functionality in my app from scratch I found that this example does still work:

```
            $pool = Pool::create();

            foreach ($xs as $i => $x) {
                $pool[] = async(function () {
                    //
                });
            }

            $pool->wait();
```

I know my issue is not well-described as I didn't find the reason why the issue occurred. Just wanted to let you know that I had an issue and gave the only relevant details I could gather. Probably you can close the issue right away.

**Comment by BohdanPetrenko** [comment]
> After I updated Composer from 1 to 2 in my application which also caused a bunch of other updates in my dependencies, a simple example does not work any more in my app:
> 
> ```
>             $pool = Pool::create();
> 
>             foreach ($xs as $i => $x) {
>                 $pool->add(function () {
>                     //
>                 });
>             }
> 
>             $pool->wait();
> ```
> 
> Tried to find out what exactly caused this simple example not to work any more but with no luck. Followed your error handling section in readme more than 10x :) I didn't get anywhere a better exception than a `ParallelError`.
> 
> When trying to re-create the functionality in my app from scratch I found that this example does still work:
> 
> ```
>             $pool = Pool::create();
> 
>             foreach ($xs as $i => $x) {
>                 $pool[] = async(function () {
>                     //
>                 });
>             }
> 
>             $pool->wait();
> ```
> 
> I know my issue is not well-described as I didn't find the reason why the issue occurred. Just wanted to let you know that I had an issue and gave the only relevant details I could gather. Probably you can close the issue right away.
```
/app/index.php:34:
object(Spatie\Async\Output\ParallelError)[8]
  protected 'message' => string '' (length=0)
  private 'string' (Exception) => string '' (length=0)
  protected 'code' => int 0
  protected 'file' => string '/app/vendor/spatie/async/src/Output/ParallelError.php' (length=53)
  protected 'line' => int 11
  private array 'trace' (Exception) => 
    array (size=6)
      0 => 
        array (size=6)
          'file' => string '/app/vendor/spatie/async/src/Process/ParallelProcess.php' (length=56)
          'line' => int 126
          'function' => string 'fromException' (length=13)
          'class' => string 'Spatie\Async\Output\ParallelError' (length=33)
          'type' => string '::' (length=2)
          'args' => 
            array (size=1)
              ...
      1 => 
        array (size=6)
          'file' => string '/app/vendor/spatie/async/src/Process/ProcessCallbacks.php' (length=57)
          'line' => int 54
          'function' => string 'resolveErrorOutput' (length=18)
          'class' => string 'Spatie\Async\Process\ParallelProcess' (length=36)
          'type' => string '->' (length=2)
          'args' => 
            array (size=0)
              ...
      2 => 
        array (size=6)
          'file' => string '/app/vendor/spatie/async/src/Pool.php' (length=37)
          'line' => int 231
          'function' => string 'triggerError' (length=12)
          'class' => string 'Spatie\Async\Process\ParallelProcess' (length=36)
          'type' => string '->' (length=2)
          'args' => 
            array (size=0)
              ...
      3 => 
        array (size=6)
          'file' => string '/app/vendor/spatie/async/src/Pool.php' (length=37)
          'line' => int 327
          'function' => string 'markAsFailed' (length=12)
          'class' => string 'Spatie\Async\Pool' (length=17)
          'type' => string '->' (length=2)
          'args' => 
            array (size=1)
              ...
      4 => 
        array (size=6)
          'file' => string '/app/vendor/spatie/async/src/Pool.php' (length=37)
          'line' => int 153
          'function' => string 'Spatie\Async\{closure}' (length=22)
          'class' => string 'Spatie\Async\Pool' (length=17)
          'type' => string '->' (length=2)
          'args' => 
            array (size=2)
              ...
      5 => 
        array (size=6)
          'file' => string '/app/index.php' (length=14)
          'line' => int 40
          'function' => string 'wait' (length=4)
          'class' => string 'Spatie\Async\Pool' (length=17)
          'type' => string '->' (length=2)
          'args' => 
            array (size=0)
              ...
  private ?Throwable 'previous' (Exception) => null
```

**Comment by FacuM** [comment]
Still relying on Composer 1 and also facing the same issue, guess this release is just broken.
