### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by neobie** [spatie/async#134]
Not sure why this thing doesn't work for me.
https://dev.to/webong/using-asynchronous-processes-in-php-7io

Not working in my Mac php, and not in my Ubuntu server php (litespeed and apache2)

Php 7.2 / 7.4
Tried everything I could.
No error thrown.
It just print out the number in sequence.
If I implement sleep(1), it just block all the process until sleep(1) is done.

**Comment by surahmans** [comment]
any updates @neobie ?

**Comment by NeonKamuy** [comment]
Hi! Same issue here. Below is the code and what I get. Doesn't seem asynchronous to me

![image](https://user-images.githubusercontent.com/56562519/115605312-6af31400-a2f3-11eb-9f5f-153324c300e5.png)
![image](https://user-images.githubusercontent.com/56562519/115605322-70505e80-a2f3-11eb-9884-b37d8ac901b8.png)

**Comment by iprastha** [comment]
have you checked whether async is supported on the machine ? using `Pool::isSupported()`
It basically checks whether you have all these functions installed and built into the php running on the machine:
pcntl_async_signals
posix_kill
proc_open

I ran into this issue and found that `posix_kill` did not exists, which I solved using `yum install php-process` (CentOS server)

**Comment by erimeilis** [comment]
Hi there! Facing kinda same issue. pcntl and also posix are enabled, but it still shows Pool::isSupported() false
