### ISSUE TITLE
Notice: serialize(): __sleep should return an array only containing the names of instance-variables to serialize.

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [spatie/async#138]
I'm getting the following error not sure where to look or how to fix it :(

`Notice: serialize(): __sleep should return an array only containing the names of instance-variables to serialize.`

**Comment by ashish8488** [comment]
> I'm getting the following error not sure where to look or how to fix it :(
> 
> `Notice: serialize(): __sleep should return an array only containing the names of instance-variables to serialize.`

I am also facing above mentioned issue. If you have fixed it, please let me also know the solution. Thanks.
