### ISSUE TITLE
posix_kill for windows

### ISSUE THREAD

**Issue by ttodua** [spatie/async#152]
Hi.
1) library's `isSupported()` static method checks whether spatie-async is supported on system. Windows misses some requirements, and one of them is `posix_kill` function. Is is possible to be a support for windows too, using [this replacement](https://github.com/laravel/horizon/issues/284) method for `posix_kill` ?  (though, main problem still stays  `pcntl_async_signals`...) 

2)  Do you have an idea, why on ubuntu 20.04 (even though pcntl module is loaded and neither it is in disabled functions) it shows `Uncaught Error: Call to undefined function pcntl_async_signals()` when calling the function (just for testing purposes)

**Comment by samuelgfeller** [comment]
I work on Windows with XAMPP. Does that mean that I cannot use this library?

**Comment by FelipeAzambuja** [comment]
i develop on my windows machine with wsl

**Comment by techno-express** [comment]
@ttodua To get this working on Windows without even messing with `posix` issue is to make a few changes in `Pool.php`, `ParentRuntime.php`, and ParallelProcess.php:

These are the main changes I made from [PR](https://github.com/spatie/async/pull/56) to get working on Windows.

// Pool.php
```php
protected static $pcntl = null;

public static function isSupported(): bool
{
  if (\is_null(self::$pcntl))
    self::$pcntl = function_exists('pcntl_async_signals')
      && function_exists('posix_kill') 
      && !self::$forceSynchronous;

  return self::$pcntl;
}

public function wait(?callable $intermediateCallback = null): array
{
  while ($this->inProgress) {
    foreach ($this->inProgress as $process) {
      if ($process->getCurrentExecutionTime() > $this->timeout) {
        $this->markAsTimedOut($process);
      }

      //if ($process instanceof SynchronousProcess) {
      // $this->markAsFinished($process);
      //}

      if (!self::$pcntl) {
        if ($process->isSuccessful()) {
          $this->markAsFinished($process);
        } elseif (! $process->isRunning() && $process->isTerminated()) {
          $this->markAsFailed($process);
        }
      }
    }

    if (! $this->inProgress) {
      break;
    }

    if ($intermediateCallback) {
      call_user_func_array($intermediateCallback, [$this]);
    }

    usleep($this->sleepTime);
  }

  return $this->results;
}
```

// ParentRuntime.php
```php
public static function createProcess($task, ?int $outputLength = null, ?string $binary = 'php'): Runnable
{
  if (! self::$isInitialised) {
    self::init();
  }

  //if (! Pool::isSupported()) {
  // return SynchronousProcess::create($task, self::getId());
  //}

  $process = new Process([
    $binary,
    self::$childProcessScript,
    self::$autoloader,
    self::encodeTask($task),
    $outputLength,
  ]);

  return ParallelProcess::create($process, self::getId());
}
```

// ParallelProcess.php
```php
public function stop($timeout = 0): self
{
  $this->process->stop($timeout); // defaults to SIGKILL = 9

  return $this;
}
```

This will resolve issue https://github.com/spatie/async/issues/157 too.
