### ISSUE TITLE
Output/Echo debugging

### ISSUE THREAD

**Issue by ttodua** [spatie/async#153]
1) in async function if i have any `echo/var_dump` whatever, the script just doesn't work. Any ideas?  I've seen https://github.com/spatie/async/issues/120 but havent this been fixed? What I should change in library manually, to enable the output? 

2) is there any way (at this moment, without waiting to change the library) to catch somehow the fact that inside async task, there was some output, and thus script was exited. How can I reliable determine, if `DoTask2()` was not fired? 
```
$pool = Pool::create();
foreach ($things as $thing) {
    $pool->add(function () use ($thing) {
        DoTask1();
        if ( rand() > 100)  echo "blabla";
        DoTask2();
    })->then(function ($output) {
        
    })->catch(function (Throwable $exception) {
        
    });
}
$pool->wait();
```
I couldnt catch such occurences, so what is the best way (without relying on `return` from async function) to detect such occurences?

**Comment by skrtdev** [comment]
It is useless to use echo/var_dump inside child process, cause it won't be shown in the output

**Comment by ttodua** [comment]
- echoing inside child process is not useless, as there are many valid scenarios when (i.e. ob_ functions) to handle or use internal output.
- even if it was useless, the post said different. It says that outputing breaks the script execution.

**Comment by skrtdev** [comment]
@ttodua i think he want to use echo cause he thinks he will appear in the output

**Comment by ttodua** [comment]
Well, there are still ways to show output from child-process.  Imagine `shell_exec/exec` which returns output from different process. Even `Parallel` or `Swoole` can show output.

**Comment by techno-express** [comment]
@ttodua  If you are still interested in a solution here is a modified one I use. 

You will need to modify the `->start()` method in ParallelProcess class where it calls on Symfony to actually **run** the `Process`. That Symfony's Process `start()/run()` methods has an [callback](https://symfony.com/doc/current/components/process.html#getting-real-time-process-output) feature to execute any on _STDERR_ or _STDOUT_ data present. 

Change `$this->process->start();` to:

	```$this->process->start(function ($type, $buffer) {
        $this->display($buffer);
    });```

Add:
```
protected $showOutput = false;
  
  public function display($buffer = null)
  {
    if ($this->showOutput && \is_string($buffer)) {
      $showing = $this->realTimeOutput($buffer);
      // Check see if PHP is running from cli (command line)
      if (!(\defined('STDIN') || (empty($_SERVER['REMOTE_ADDR']) && !isset($_SERVER['HTTP_USER_AGENT']) && \count($_SERVER['argv']) > 0)))
        $showing = \htmlspecialchars($showing, \ENT_COMPAT, 'UTF-8');

      \printf('%s', $showing);
    }
  }

  // You might not need this
  protected function realTimeOutput($buffer = null)
  {
    if (!empty($buffer)) {
      $realOutput = @\unserialize(\base64_decode($buffer));
      if (!$realOutput) {
        $realOutput = $buffer;
      }

      return \str_replace('Tjs=', '', $realOutput);
    }
  }

  public function displayOn(): self
  {
    $this->showOutput = true;

    return $this;
  }

  public function displayOff(): self
  {
    $this->showOutput = false;

    return $this;
  }
```

**Comment by ttodua** [comment]
@techno-express  many thanks for sharing that. I will try to give it a shot when I'll return to the project I was working onto .
