### ISSUE TITLE
clearly document this does not support windows!

### ISSUE THREAD

**Issue by kpconnell** [spatie/async#157]
The dependency on pcntl - https://www.php.net/manual/en/pcntl.installation.php 

leaves windows out.

**Comment by DavidBruchmann** [comment]
This does not concern the framework itself. In the README is stated:  
`If the required extensions (pcntl and posix) are not installed in your current PHP runtime, the Pool will automatically fallback to synchronous execution of tasks.`

**Comment by DavidBruchmann** [comment]
![image](https://user-images.githubusercontent.com/999146/126893218-12c8a0fa-355d-4718-85cb-740edb832034.png)

**Comment by kpconnell** [comment]
> This does not concern the framework itself. In the README is stated:
> `If the required extensions (pcntl and posix) are not installed in your current PHP runtime, the Pool will automatically fallback to synchronous execution of tasks.`
> Nevertheless, I agree that a related hint might be useful.

Right, and exactly zero people want to use an async library synchronously.
