### ISSUE TITLE
Support of PHP versions?

### ISSUE THREAD

**Issue by stephanvierkant** [spatie/async#175]
I see this library still supports PHP 7.1, which is End of Life (EOL) for a long time. Even 7.3 is EOL as of today.

What's the policy about PHP support? The only [supported versions](https://www.php.net/supported-versions.php) are 7.4, 8.0 and 8.1

In my opinion libraries should drop support of PHP versions that are end of life, because it makes contributing to this library much easier.

**Comment by Stevemoretz** [comment]
> I see this library still supports PHP 7.1, which is End of Life (EOL) for a long time. Even 7.3 is EOL as of today.
> 
> What's the policy about PHP support? The only [supported versions](https://www.php.net/supported-versions.php) are 7.4, 8.0 and 8.1
> 
> In my opinion libraries should drop support of PHP versions that are end of life, because it makes contributing to this library much easier.

Doesn't make a lot of sense if your features don't rely on new features, and it supports old versions then it does :)

**Comment by stephanvierkant** [comment]
About 1% is using PHP 7.1: https://packagist.org/packages/spatie/async/php-stats#1.5. More people are using PHP 8.1.

New features (such as typed properties, return types, parameter types) aren't required and don't bring new capabilities, but they improve readability/maintainability of code.

**Comment by Stevemoretz** [comment]
> About 1% is using PHP 7.1: https://packagist.org/packages/spatie/async/php-stats#1.5. More people are using PHP 8.1.
> 
> New features (such as typed properties, return types, parameter types) aren't required and don't bring new capabilities, but they improve readability/maintainability of code.

Makes sense haven't had seen those statistics on this package sorry :)
