### ISSUE TITLE
 Return type of Spatie\Async\Pool::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool

### ISSUE THREAD

**Issue by gopibabus** [spatie/async#191]
**Piece of code that I am trying to execute**

```php
use Spatie\Async\Pool;

$pool = Pool::create();

foreach (range(1, 5) as $i) {
    $pool[] = async(function () {
        usleep(random_int(10, 1000));

        return 2;
    })->then(function (int $output) {
        $this->counter += $output;
    });
}

await($pool);
```

**Installed Version of PHP**
8.0.*

**Error Screenshot:**
![image](https://user-images.githubusercontent.com/21990337/169495920-1cbf26c2-adeb-4b59-9b93-2d770588e5de.png)

I hope this helps you. Please let me know if you need any further details. Thanks for your contribution.

**Comment by alexander-schreiner** [comment]
Same issue with PHP 8.1.7

**Comment by alexander-schreiner** [comment]
https://github.com/spatie/async/pull/184 would fix this issue
