### ISSUE TITLE
   Spatie\Async\Output\ParallelError 

### ISSUE THREAD

**Issue by alexgarciab** [spatie/async#194]
**Spatie\Async\Output\ParallelError**

  at vendor/spatie/async/src/Output/ParallelError.php:11
      7▕ class ParallelError extends Exception
      8▕ {
      9▕     public static function fromException($exception): self
     10▕     {
  ➜  11▕         return new self($exception);
     12▕     }
     13▕ 
     14▕     public static function outputTooLarge(int $bytes): self
     15▕     {

\+5 vendor frames 
  6   app/Console/Commands/read.php:48
      Spatie\Async\Pool::wait()

\+13 vendor frames 
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

Why is this happening?

**Comment by alexgarciab** [comment]
No solution found

**Comment by RaiserWeb** [comment]
Same error

**Comment by safarovitch** [comment]
Same error

**Comment by ijazahmedbhatti** [comment]
Same error

**Comment by saken14** [comment]
same error

**Comment by saken14** [comment]
https://github.com/spatie/async/issues/186#issuecomment-1767217228 this solution solved the problem.
