### ISSUE TITLE
How to use external functions and variables?

### ISSUE THREAD

**Issue by iyamk** [spatie/async#202]
I make:
```
$pool[] = async(function () {
    global $vk;
    $vk->listen();
    return 2;
})->then(function (int $output) {
    echo 'ok';
});
```
And it throws an error because vk is NULL! it is in the global scope

And text output in a function is not displayed in the console

**Comment by bhojkapderas** [comment]
@iyamk 

$global $vk;
$pool[] = async(function () use ($vk) {
    $vk->listen();
    return 2;
})->then(function (int $output) {
    echo 'ok';
});
