### ISSUE TITLE
Deprecated: Return type of Symfony\Component\Process\Process::getIterator($flags = 0)

### ISSUE THREAD

**Issue by wf58585858** [spatie/async#203]
I encountered the following error using this package in my project, and it happened on PHP 8.0, 8.1, and 8.2.

`Deprecated: Return type of Symfony\Component\Process\Process::getIterator($flags = 0) should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/6005/others/missions/vendor/symfony/process/Process.php on line 567`

`Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/6005/others/missions/vendor/symfony/process/Process.php on line 1712`

```
{
    "require"  : {
        "treffynnon/command-wrap"       : "^1.0",
        "nette/utils"                   : "^3.1",
        "monolog/monolog"               : "^2.4",
        "coduo/php-humanizer"           : "^3.0",
        "opis/closure"                  : "^3.6",
        "symfony/cache"                 : "v6.0.19",
        "php-amqplib/php-amqplib"       : "^3.5",
        "hidehalo/nanoid-php"           : "^1.1",
        "anujrnair/php-json-marshaller" : "^1.0",
        "php-di/php-di"                 : "^7.0",
        "ext-redis"                     : "*",
        "spatie/async": "^1.5",
        "guzzlehttp/guzzle": "^7.5"
    },
    "autoload" : {
        "psr-4" : {
            ""    : "src/",
            "app\\" : "app/"
        }
    }

}
```

```
<?php
    require 'vendor/autoload.php';

    use Spatie\Async\Pool;

    $pool = Pool::create();

    foreach (range(1 , 5) as $thing)
    {
        $pool->add(function() use ($thing){

            sleep(2);
            echo $thing;

            return $thing . ' -- ' . PHP_EOL;
        })->then(function($output){
            echo $output . PHP_EOL;

        })->catch(function(Throwable $exception){
            // Handle exception
        });
    }

    $pool->wait();
```

**Comment by santossoares** [comment]
Remove the echo $thing, line from the add method.

$pool->add(function() use ($thing){

            sleep(2);
            //echo $thing;
            
            
            
 Actually, using echo or var_dump inside the add method, breaks the code. The $output variable gets null. This is probably causing the error.
