### ISSUE TITLE
Cannot serialize Symfony\Component\HttpClient\Response\AsyncResponse

### ISSUE THREAD

**Issue by Mahdillah** [spatie/async#208]
I want to get content from the array of responses and throw BadMethodCallException
```
foreach ($result as $provider_tag => $res) {
    $pool->add(function () use ($res, $provider_tag) {
        $test = $res[0]->getContent();
        return $test;
    })->then(function ($test) {
        echo $test;
    });
}
```
Please help me with this issue.

**Comment by AlexVanderbist** [comment]
Hi there, internally the output from each child process gets serialised (see https://github.com/spatie/async/blob/master/src/Runtime/ChildRuntime.php#L28C34-L28C34). This means that whatever you return from the pool task must be serializable by PHP using `serialize`.

For your specific example, I'd stream the contents of the `AsyncResponse` and return the string instead:
```php
// Get the stream of the AsyncResponse
$stream = $asyncResponse->toStream();

// Read the contents of the stream
$contents = stream_get_contents($stream);

// Close the stream
fclose($stream);

// Return the contents
return $contents;
```
