### ISSUE TITLE
Bubbling up of exceptions fails

### ISSUE THREAD

**Issue by kirkbushell** [spatie/async#210]
Firstly, can I just see - fantastic package! I see it being leveraged in laravel-async and it's made some operations of ours incredibly performant as a result. Thank you and well done! :)

When an exception is captured, the ChildRuntime code has a block that looks like this:

```php
} catch (Throwable $exception) {
    require_once __DIR__.'/../Output/SerializableException.php';

    $output = new \Spatie\Async\Output\SerializableException($exception);

    fwrite(STDERR, base64_encode(serialize($output)));

    exit(1);
}
```

Unfortunately, I've noticed that it fails at the fwrite call:

`[2023-08-02 13:13:11] local.ERROR: fwrite(): Write of 3360 bytes failed with errno=32 Broken pipe {"exception":"[object] (ErrorException(code: 0): fwrite(): Write of 3360 bytes failed with errno=32 Broken pipe at /Users/.../vendor/spatie/async/src/Runtime/ChildRuntime.php:42)`

**Comment by AlexVanderbist** [comment]
Hi @kirkbushell, thanks for reporting this issue. Unfortunately, I couldn't immediately reproduce it. Could you please provide some example code in this issue? Or even better: submit a PR containing a failing test. Also, can you let me know what version of PHP and the package you are using? Thanks!
