### ISSUE TITLE
php 8.1.10 is error

### ISSUE THREAD

**Issue by jian-kuang** [spatie/async#211]
Cannot assign Laravel\SerializableClosure\Serializers\Native to property Symfony\Component\Console\Input\InputArgument::$suggestedValues of type Closure|array

  at vendor/laravel/serializable-closure/src/Serializers/Native.php:286
    282▕                     if (is_array($value) || is_object($value)) {
    283▕                         static::wrapClosures($value, $storage);
    284▕                     }
    285▕ 
  ➜ 286▕                     $property->setValue($data, $value);
    287▕                 }
    288▕             } while ($reflection = $reflection->getParentClass());
    289▕         }
    290▕     }

      +11 vendor frames 
  12  [internal]:0
      Laravel\SerializableClosure\Serializers\Native::__serialize()

      +1 vendor frames 
  14  [internal]:0

**Comment by AlexVanderbist** [comment]
Could you please provide example code, including the PHP version and package version you're using? It would be even better if you could create a pull request with a failing test. Thank you!
