### ISSUE TITLE
Issue with SIGCHLD handling in PHP Version 8.1.24

### ISSUE THREAD

**Issue by sibadevelopment** [spatie/async#217]
The pcntl signal handling is not working in PHP Version 8.1.24.

I don't know what is planned in future PHP versions but I would recommend to change the following line

**if (phpversion() === '8.1.22' || phpversion() === '8.2.9')** 

to this:

**if (version_compare(PHP_VERSION, '8.1.22') >= 0 || version_compare(PHP_VERSION, '8.2.9') >= 0)**

**Comment by matthi4s** [comment]
The issue that is fixed in the lines that you are referring to is only specific to those two versions. It was reverted in PHP 8.1.23 and therefore the workaround should not be necessary or work in any other version.

**Comment by sibadevelopment** [comment]
I have read from that it should be reverted with PHP version 8.1.23. But for me it's not working without the fix on a Ubuntu machine with PHP 8.1.24 (cli) (built: Oct  6 2023 09:46:42) (NTS) 8.1.24. So was it changed again from version 8.1.23 to version 8.1.24?
