### ISSUE TITLE
Module 'pcntl' already loaded 

### ISSUE THREAD

**Issue by brendt** [spatie/async#36]
@zelin wasn't able to create an issue, so I'm doing it for you.

```
#0 Pushbot/src/Pushbot/Async/Process/ParallelProcess.php(126): Pushbot\Async\Output\ParallelError::fromException('PHP Warning:  M...')
#1 Pushbot/src/Pushbot/Async/Process/ProcessCallbacks.php(51): Pushbot\Async\Process\ParallelProcess->resolveErrorOutput()
#2 Pushbot/src/Pushbot/Async/Pool.php(201): Pushbot\Async\Process\ParallelProcess->triggerError()
#3 Pushbot/src/Pushbot/Async/Pool.php(297): Pushbot\Async\Pool->markAsFailed(Object(Pushbot\Async\Process\ParallelProcess))
#4 Pushbot/src/Pushbot/Async/Pool.php(128): Pushbot\Async\Pool->Pushbot\Async\{closure}(20, Array)
#5 Pushbot/src/Pushbot/Pushbot.php(421): Pushbot\Async\Pool->wait()
```

**Comment by brendt** [comment]
@zelin the real error is truncated in your log:

```
Pushbot\Async\Output\ParallelError::fromException('PHP Warning:  M...')
```

It's the warning message that'll tell you what's wrong, any chance you can get your hands on a non-truncated version?

You can debug errors by adding `->catch` on a task: https://github.com/spatie/async#error-handling

**Comment by zelin** [comment]
Okay, had to do some changes to find the error.
Async\Output\ParallelError: PHP Warning:  Module 'pcntl' already loaded in Unknown on line 0

I recently added pcntl extension on my mac via  brew install homebrew/php/php7-pcntl

**Comment by brendt** [comment]
I'm afraid there's little information in that exception do you have the full trace available? Also, can you share the code you're trying to run in parallel?

**Comment by zelin** [comment]
Doesn't matter if i run anything or not.  just copied the code you have used as sample.


```
if($sync == false)
        {
            $supported = Pool::isSupported();
            echo $supported;
            if($supported)
            {
                @static::$pool   = Pool::create();
                static::$sync   = $sync;
            }
            else
                static::$sync   = false;            
        }
        else
            static::$sync       = $sync;

static::$pool->add(function () use ($value)    // $value is an array
                {
                                        return '';

                })->then(function ($output) 
                {
                                   
                })->catch(function (Throwable $exception) 
                {
                    echo $exception; // I have placed the exception above.
                });    
```

**Comment by brendt** [comment]
Something is probably wrong on your system, are you in the position to spin up a VM like Docker or Vagrant? If it works in a clean environment you'll be able to more quickly pinpoint the problem on your machine.

**Comment by brendt** [comment]
I'm going to close this issue, as there doesn't seem to be any input anymore.
