### ISSUE TITLE
InvalidArgumentException  : Unknown setter 'date'

### ISSUE THREAD

**Issue by brnmonteiro** [spatie/async#37]
When I add a pool, a error is throwed:

```php
   InvalidArgumentException  : Unknown setter 'date'

  at vendor/nesbot/carbon/src/Carbon/Carbon.php:1011
    1007|                 $this->setTimezone($value);
    1008|                 break;
    1009|
    1010|             default:
  > 1011|                 throw new InvalidArgumentException(sprintf("Unknown setter '%s'", $name));
    1012|         }
    1013|     }
    1014|
    1015|     /**

  Exception trace:

  1   Carbon\Carbon::__set("date", "2018-05-14 09:42:26.369021")
      [internal]:0

  2   ReflectionProperty::setValue(Object(Illuminate\Support\Carbon), "2018-05-14 09:42:26.369021")
      vendor/opis/closure/src/SerializableClosure.php:359
```

**Comment by brendt** [comment]
Hi @brnmonteiro , I don't think this error has to do with the async package. At least, it's not clear from the code snippet you've linked. 

Please refer to this post to know what kind of information is needed for a good issue: https://sebastiandedeyne.com/a-good-issue ; furthermore, you can read the [README](https://github.com/spatie/async/blob/master/README.md) to know how to properly use the package.

I'm closing this issue for now, feel free to reply with more information if you think this is related to `spatie/async`.

**Comment by platformsfx** [comment]
Same here:

   InvalidArgumentException  : Unknown setter 'date'

  at /Users/{PH}/Sites/{PH}/{PH}/vendor/nesbot/carbon/src/Carbon/Carbon.php:1202
    1198|                 $this->setTimezone($value);
    1199|                 break;
    1200|
    1201|             default:
  > 1202|                 throw new InvalidArgumentException(sprintf("Unknown setter '%s'", $name));
    1203|         }
    1204|     }
    1205|
    1206|     /**

  Exception trace:

  1   Carbon\Carbon::__set("date", "2018-10-09 13:30:51.266615")
      [internal]:0

  2   ReflectionProperty::setValue(Object(Illuminate\Support\Carbon), "2018-10-09 13:30:51.266615")
      /Users/{PH}/Sites/{PH}/{PH}/vendor/opis/closure/src/SerializableClosure.php:397


code: 
$sPool = SPool::create()->concurrency(20);

$sPool[] = async(function () use ($msg) {

                                        // Some process here
                                    
                                })->then(function ($output) {
                                    // Handle success
                                    \Log::info("OUT: " . $output);
                                })->catch(function (\Exception $exception) {
                                    // Handle exception
                                     \Log::info($exception->getMessage());
                                });

await($sPool);

AND WHILE I used try catch for the SerializableClosure.php:397 I Got this: 

[2018-10-09 13:18:29] local.INFO: Unknown setter 'date'  
[2018-10-09 13:18:29] local.INFO: Unknown setter 'timezone_type'  
[2018-10-09 13:18:29] local.INFO: DateTime::setTimezone(): The DateTime object has not been correctly initialized by its constructor

**Comment by platformsfx** [comment]
Same here:

```
 InvalidArgumentException : Unknown setter 'date'
 at /Users/{PH}/Sites/{PH}/{PH}/vendor/nesbot/carbon/src/Carbon/Carbon.php:1202
 1198| $this->setTimezone($value);
 1199| break;
 1200|
 1201| default:
 1202| throw new InvalidArgumentException(sprintf("Unknown setter '%s'", $name));
 1203| }
 1204| }
 1205|
 1206| /**
```

Exception trace:

1 Carbon\Carbon::__set("date", "2018-10-09 13:30:51.266615")
[internal]:0

2 ReflectionProperty::setValue(Object(Illuminate\Support\Carbon), "2018-10-09 13:30:51.266615")
/Users/{PH}/Sites/{PH}/{PH}/vendor/opis/closure/src/SerializableClosure.php:397


code:
```
    $sPool = SPool::create()->concurrency(20);
    $sPool[] = async(function () use ($msg){
                             // Some process here
                       })->then(function ($output) {
                            // Handle success
                            \Log::info("OUT: " . $output);
                      })->catch(function (\Exception $exception) {
                         // Handle exception
                        \Log::info($exception->getMessage());
                    });
    await($sPool);
```


AND WHILE I used try catch for the SerializableClosure.php:397 I Got this:

[2018-10-09 13:18:29] local.INFO: Unknown setter 'date'
[2018-10-09 13:18:29] local.INFO: Unknown setter 'timezone_type'
[2018-10-09 13:18:29] local.INFO: DateTime::setTimezone(): The DateTime object has not been correctly initialized by its constructor

**Comment by brendt** [comment]
@platformsfx please read my previous comment on the topic of clear issues.
