### ISSUE TITLE
error: undefined function Spatie\Async\pcntl_async_signals() 

### ISSUE THREAD

**Issue by flik** [spatie/async#39]
**getting this error**:

(1/1) FatalThrowableErrorCall to undefined function Spatie\Async\pcntl_async_signals()
--
in Pool.php line 263
at Pool->registerListener()in Pool.php line 42
at Pool->__construct()in Pool.php line 52

**here is my code**: 
               ```php
$pool = Pool::create();
 
                $pool->add(function () use ($thing) { 
                    $token = (array)json_decode($this->getRefreshedToken($user));
                    \Log::info(json_encode( $token));
                })->then(function ($output) {
                   // return $output;
                    // Handle success
                      \Log::info($output);
                })->catch(function (Throwable $exception) {
                    // Handle exception
                });
```

**Comment by brendt** [comment]
Looks like you don't have the `pcntl` extension installed.

**Comment by yashc1998** [comment]
How to install it?

**Comment by brendt** [comment]
pcntl doesn't work on Windows. This package only supports Unix systems.

**Comment by Szymoon202** [comment]
Im bit confused. Im working at php 7.2 version, pcntl extension is supported but the same error appears. What should I do?

**Comment by pietervanheijningen** [comment]
> How to install it in windows?

if you install php in windows subsystem for linux (wsl) it seems to be enabled by default
