### ISSUE TITLE
Can't install on laravel 5.4

### ISSUE THREAD

**Issue by pula2000** [spatie/async#48]
When I run the command (composer require spatie/async) it gives the below output - 
Problem 1
    - Installation request for spatie/async ^0.0.4 -> satisfiable by spatie/async[0.0.4].
    - Conclusion: remove symfony/process v3.2.6
    - Conclusion: don't install symfony/process v3.2.6
    - spatie/async 0.0.4 requires symfony/process ^3.3 || ^4.0 -> satisfiable by symfony/process[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6].
    - Can only install one of: symfony/process[v3.3.0, v3.2.6].
    - Can only install one of: symfony/process[v3.3.1, v3.2.6].
    - Can only install one of: symfony/process[v3.3.10, v3.2.6].
    - Can only install one of: symfony/process[v3.3.11, v3.2.6].
    - Can only install one of: symfony/process[v3.3.12, v3.2.6].
    - Can only install one of: symfony/process[v3.3.13, v3.2.6].
    - Can only install one of: symfony/process[v3.3.14, v3.2.6].
    - Can only install one of: symfony/process[v3.3.15, v3.2.6].
    - Can only install one of: symfony/process[v3.3.16, v3.2.6].
    - Can only install one of: symfony/process[v3.3.17, v3.2.6].
    - Can only install one of: symfony/process[v3.3.18, v3.2.6].
    - Can only install one of: symfony/process[v3.3.2, v3.2.6].
    - Can only install one of: symfony/process[v3.3.3, v3.2.6].
    - Can only install one of: symfony/process[v3.3.4, v3.2.6].
    - Can only install one of: symfony/process[v3.3.5, v3.2.6].
    - Can only install one of: symfony/process[v3.3.6, v3.2.6].
    - Can only install one of: symfony/process[v3.3.7, v3.2.6].
    - Can only install one of: symfony/process[v3.3.8, v3.2.6].
    - Can only install one of: symfony/process[v3.3.9, v3.2.6].
    - Can only install one of: symfony/process[v3.4.0, v3.2.6].
    - Can only install one of: symfony/process[v3.4.1, v3.2.6].
    - Can only install one of: symfony/process[v3.4.10, v3.2.6].
    - Can only install one of: symfony/process[v3.4.11, v3.2.6].
    - Can only install one of: symfony/process[v3.4.12, v3.2.6].
    - Can only install one of: symfony/process[v3.4.13, v3.2.6].
    - Can only install one of: symfony/process[v3.4.14, v3.2.6].
    - Can only install one of: symfony/process[v3.4.15, v3.2.6].
    - Can only install one of: symfony/process[v3.4.16, v3.2.6].
    - Can only install one of: symfony/process[v3.4.17, v3.2.6].
    - Can only install one of: symfony/process[v3.4.2, v3.2.6].
    - Can only install one of: symfony/process[v3.4.3, v3.2.6].
    - Can only install one of: symfony/process[v3.4.4, v3.2.6].
    - Can only install one of: symfony/process[v3.4.5, v3.2.6].
    - Can only install one of: symfony/process[v3.4.6, v3.2.6].
    - Can only install one of: symfony/process[v3.4.7, v3.2.6].
    - Can only install one of: symfony/process[v3.4.8, v3.2.6].
    - Can only install one of: symfony/process[v3.4.9, v3.2.6].
    - Can only install one of: symfony/process[v4.0.0, v3.2.6].
    - Can only install one of: symfony/process[v4.0.1, v3.2.6].
    - Can only install one of: symfony/process[v4.0.10, v3.2.6].
    - Can only install one of: symfony/process[v4.0.11, v3.2.6].
    - Can only install one of: symfony/process[v4.0.12, v3.2.6].
    - Can only install one of: symfony/process[v4.0.13, v3.2.6].
    - Can only install one of: symfony/process[v4.0.14, v3.2.6].
    - Can only install one of: symfony/process[v4.0.2, v3.2.6].
    - Can only install one of: symfony/process[v4.0.3, v3.2.6].
    - Can only install one of: symfony/process[v4.0.4, v3.2.6].
    - Can only install one of: symfony/process[v4.0.5, v3.2.6].
    - Can only install one of: symfony/process[v4.0.6, v3.2.6].
    - Can only install one of: symfony/process[v4.0.7, v3.2.6].
    - Can only install one of: symfony/process[v4.0.8, v3.2.6].
    - Can only install one of: symfony/process[v4.0.9, v3.2.6].
    - Can only install one of: symfony/process[v4.1.0, v3.2.6].
    - Can only install one of: symfony/process[v4.1.1, v3.2.6].
    - Can only install one of: symfony/process[v4.1.2, v3.2.6].
    - Can only install one of: symfony/process[v4.1.3, v3.2.6].
    - Can only install one of: symfony/process[v4.1.4, v3.2.6].
    - Can only install one of: symfony/process[v4.1.5, v3.2.6].
    - Can only install one of: symfony/process[v4.1.6, v3.2.6].
    - Installation request for symfony/process (locked at v3.2.6) -> satisfiable by symfony/process[v3.2.6].
Installation failed, reverting ./composer.json to its original content.

**Comment by brendt** [comment]
We don't support legacy Laravel versions. We highly advice always updating your projects one or two weeks after a new Laravel update comes out.
