### ISSUE TITLE
Parallel Error

### ISSUE THREAD

**Issue by Elhellawy** [spatie/async#51]
I installed the package for a week and it gives me the same error
i created simple api to test the package
i have already  posix and pcntl extentions and i called isSupported function that came with the packege 
and it returned true 

my operting system ubuntu 16.04
php version 7.2

that is my code

`Route::get('spatie',function (){

    $pool = Pool::create();
    $things=[1,2,3];
    foreach ($things as $thing) {
        $pool->add(function () use ($thing) {
            return $thing;
        })->then(function ($output) {
            return $output;
        })->catch(function (Throwable $exception) {
            dd($exception);
        });
    }

    dd($pool->wait());
});`

and this is the error came to me 
![spatie](https://user-images.githubusercontent.com/9483919/48897374-99364600-ee52-11e8-9525-69689682aa42.png)

**Comment by brendt** [comment]
This package cannot be run in a HTTP request: http://php.net/manual/en/intro.pcntl.php

**Comment by Elhellawy** [comment]
So When i use it

**Comment by Elhellawy** [comment]
i want to use it with my api

**Comment by brendt** [comment]
It won't be so simple. Amp supports asynchronicity in web requests, but I believe you'll need to run their PHP server implementation, instead of apache or nginx: https://github.com/amphp/amp

**Comment by Elhellawy** [comment]
SoooOO When Should i use it
