### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by fedeisas** [spatie/async#54]
Is there a limit on concurrency? I can't seem to make this library create more 20 concurrent processes. I checked the getter/setter and code seems correct. I tried many combinations of concurrency and sleepTime but still no change.

Also, what are the future plans on allowing many tasks per process? I saw an old issue and there's still a variable for that on the `Pool` class.

**Comment by brendt** [comment]
The pool can be configured like so:

```php
$pool = Pool::create()
    ->concurrency(2000)
```

But you'll have to take into account the limits of the underlying OS. It'll probably not allow spawning 2000 child processes.

At this moment there are no plans to allow multiple tasks per process. If this a requirement, I suggest looking at Amp: https://github.com/amphp/amp
