### ISSUE TITLE
Hi, upgrading your PHP version also requires you to upgrade your PHP extensions. Unfortunately that's not this package's concern.

### ISSUE THREAD

**Issue by krtrth** [spatie/async#58]
Hi, upgrading your PHP version also requires you to upgrade your PHP extensions. Unfortunately that's not this package's concern.

_Originally posted by @brendt in https://github.com/spatie/async/issues/57#issuecomment-462741217_

yeah but I am referencing here to symfony I have symfony version 3.1.9 it is giving me error

**Comment by brendt** [comment]
Please don't open new issues after the previous one has been closed. 

You're in the process of upgrading to a new PHP version, please do some research online to know what's happening, this repository is not a support line for all things PHP related.

**Comment by krtrth** [comment]
it is not php related because composer update is working fine if I update symfony I have to update my laravel and I don't want to do that and your repository is asking for symfony version 3.3 or higher

**Comment by brendt** [comment]
> and I don't want to do that

That means you cannot use this package

**Comment by krtrth** [comment]
so there is no way I can use this package for my laravel ? any other package suggestion to achieve same goal

**Comment by brendt** [comment]
> so there is no way I can use this package for my laravel

That's correct

> any other package suggestion to achieve same goal

Laravel has built-in queue jobs, this might be enough for you?

**Comment by krtrth** [comment]
ok I'll try that
