### ISSUE TITLE
PHP Startup: Unable to load dynamic library

### ISSUE THREAD

**Issue by leocarmo** [spatie/async#59]
Hello. I need help here.

- PHP 7.3.2

My code:
`
        dump('supported: ' . Pool::isSupported());

        dump('posix: ' . extension_loaded('posix'));
        dump('pcntl: ' . extension_loaded('pcntl'));

        dump('Start pool: ' . Carbon::now()->format('Y-m-d H:i:s'));
        $pool = Pool::create();
        dump($pool);

        for ($i = 0; $i <= 5; $i++) {

            dump('Task '.$i.': ' . Carbon::now()->format('Y-m-d H:i:s'));
            $pool->add(function () use ($i) {
                sleep($i);
                return $i;
            })->then(function ($output) {
                $this->results[] = $output;
            })->catch(function (\Throwable $exception) {
                ApmReportExceptionService::report($exception);
            });

        }

        dump('Wait: ' . Carbon::now()->format('Y-m-d H:i:s'));
        $pool->wait();
        dump('End: ' . Carbon::now()->format('Y-m-d H:i:s'));
`

My output:
![image](https://user-images.githubusercontent.com/21243754/53241700-43f01780-3681-11e9-8217-a47b2fd015af.png)
![image](https://user-images.githubusercontent.com/21243754/53241593-e065ea00-3680-11e9-9204-e525188fd825.png)

My exception message:
`
PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqlnd.so' (tried: /usr/lib/php7/modules/mysqlnd.so (Error relocating /usr/lib/php7/modules/mysqlnd.so: _zend_hash_str_update: symbol not found), /usr/lib/php7/modules/mysqlnd.so.so (Error loading shared library /usr/lib/php7/modules/mysqlnd.so.so: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqli.so' (tried: /usr/lib/php7/modules/mysqli.so (Error relocating /usr/lib/php7/modules/mysqli.so: _zend_hash_str_update: symbol not found), /usr/lib/php7/modules/mysqli.so.so (Error loading shared library /usr/lib/php7/modules/mysqli.so.so: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql.so' (tried: /usr/lib/php7/modules/pdo_mysql.so (Error relocating /usr/lib/php7/modules/pdo_mysql.so: _zval_ptr_dtor: symbol not found), /usr/lib/php7/modules/pdo_mysql.so.so (Error loading shared library /usr/lib/php7/modules/pdo_mysql.so.so: No such file or directory)) in Unknown on line 0
`

Tks!

**Comment by mrfu2** [comment]
Sigh... Can we limit issues for this library to issues for this library only?
This is not a public "pls hlp" forum for PHP...

Regarding your specific issue, your php.ini is trying to load "mysqlnd.so" which cannot be located. (it clearly says so...)
Disable it in your php.ini (add # in front) or remove the ".so" from it.

Also, don't create a new issue ticket, go to StackOverflow instead.

**Comment by brendt** [comment]
I'm afraid I share @mrfu2's opinion, PHP configuration problems are out of the scope of this issue.

**Comment by leocarmo** [comment]
ok, np tks
