### ISSUE TITLE
Display output of forked scripts

### ISSUE THREAD

**Issue by DariusIII** [spatie/async#63]
I have scripts that have their own output messages (informative kind) that are not shown when scripts are forked with async.

Is there a way to get output of forked scripts with async library? 

I know that there is an `getOutput()` function, but it throws an error that process needs to be started first to use the `getOutput()` on it.

I have used barracudanetworks/fork-daemon before i started using spatie/async and i was passing `exec/passthrough or shell_exec` depending on user selection how to display output of scripts, or not to display it at all.

I do use `->then` to display message after script is done, but it is not quite there for my use case.

**Comment by brendt** [comment]
I'm afraid that if this doesn't meet your needs, this library won't be a good match:

> I do use ->then to display message after script is done, but it is not quite there for my use case.
