### ISSUE TITLE
Not working out of the box

### ISSUE THREAD

**Issue by sstepanovvl** [spatie/async#64]
Laravel 5.7
PHP 7.1.25
spatie/async 1.0.0

> Opis\Closure\SecurityException: The serialized closure is signed. Make sure you use a security provider for both serialization and unserialization.

```
$pool = new Pool();
$i = 5;
while ($i) {
     $pool->add(function () use ($i) {
          echo $i;
          sleep(10);
     });
     $i--;
}

$pool->wait();
```

**Comment by brendt** [comment]
Duplicate: https://github.com/spatie/async/issues/52#issuecomment-443354354
