### ISSUE TITLE
Synchronous fallback confuse

### ISSUE THREAD

**Issue by vuongxuongminh** [spatie/async#65]
In document i found:

`If the required extensions (pcntl and posix) are not installed in your current PHP runtime, the Pool will automatically fallback to synchronous execution of tasks.`

But currently when not have required extensions an error will be throw because a `Pool` call `registerListener` in the constructor should we check `isSupported` before call it? If not, why we not add it to `require` section in `composer.json`?

**Comment by brendt** [comment]
I'd accept a PR to fix this
