### ISSUE TITLE
Can not handle multi error events

### ISSUE THREAD

**Issue by vuongxuongminh** [spatie/async#67]
When an exception throw in child runtime process only one event can trigger because a break statement [#67 ProcessCallbacks](https://github.com/spatie/async/blob/master/src/Process/ProcessCallbacks.php#L67), I think we should remove it because some case need to catch multi exception like try catch, an exception throwed may match multi `is_a` parents exception and `success`, `timeout` can handle multi events but `error` is not?

**Comment by brendt** [comment]
That's not how PHP's try/catch works though: https://3v4l.org/ACB3M

The goal of this feature was to mimic PHP's try/catch as close as possible. I don't think we should change it.
