### ISSUE TITLE
Eloquent operations inside pool

### ISSUE THREAD

**Issue by anbu369** [spatie/async#68]
How do I do eloquent operations inside the pool function? I tried doing it but it doesn't work or throw any errors.

**Comment by brendt** [comment]
Tasks run in the pool are separate PHP processes. This means you need to bootstrap Laravel again in them. Please refer to https://github.com/spatie/async#working-with-tasks

**Comment by brendt** [comment]
As a side note: bootstrapping Laravel is costly in terms of performance. Async processes should be used for calculation or IO heavy operations. I think what you're looking for is Laravel's queuing system: https://laravel.com/docs/5.8/queues
