### ISSUE TITLE
Bug when waiting synchronous process

### ISSUE THREAD

**Issue by vuongxuongminh** [spatie/async#69]
An exception throw when `wait` synchronous process [Pool #132](https://github.com/spatie/async/blob/master/src/Pool.php#L132) because execution time only set when task not throw exception [SynchronousProcess #50](https://github.com/spatie/async/blob/master/src/Process/SynchronousProcess.php#L50). I think we should set `executionTime` in `finally` block of try catch.

**Comment by brendt** [comment]
Feel free to submit a PR!

**Comment by brendt** [comment]
Fixed with 1.0.2: https://github.com/spatie/async/releases/tag/1.0.2
