### ISSUE TITLE
PDO instance?

### ISSUE THREAD

**Issue by AdamSEY** [spatie/async#70]
if my function has a MySQL PDO I get failed to serialize PDO instance

**Comment by brendt** [comment]
Async tasks are new PHP processes, you cannot serialize everything. You need to bootstrap your process manually: https://github.com/spatie/async#working-with-tasks

**Comment by AdamSEY** [comment]
can you explain a little bit about how to use tasks it's not quite clear for me, do I pass the PDO instance in the configure function? also what is the run function for? can I find some more in-depth documentation 



use Spatie\Async\Task;

class MyTask extends Task
{
    public function configure()
    {
      $this->myPDO = $myPDOInstance;
    }

    public function run()
    {
        // Do the real work here.
    }
}

// Add the task to the pool
$pool->add(new MyTask());

**Comment by brendt** [comment]
I believe this explanation is helpful: https://github.com/spatie/async/issues/23#issuecomment-358938108

**Comment by AdamSEY** [comment]
Yeah, that's really helpful. thanks a lot

**Comment by brendt** [comment]
You're welcome!
