### ISSUE TITLE
Error in laravel 5.8 installation

### ISSUE THREAD

**Issue by jafar690** [spatie/async#75]
i just installed this package in larave 5.8 and i get the following error

`PHP Deprecated:  Passing a command as string when creating a "Symfony/Component/Process/Process" instance is deprecated since Symfony 4.2, pass it as an array of its arguments instead, or use the "Process::fromShellCommandline()" constructor if you need features provided by the shell. in /home/benjamingakami/jobs/syntax/dropexpress/vendor/symfony/process/Process.php on line 147`

**Comment by skeeith** [comment]
Same here, I have the same problem with this Laravel 5.8

**Comment by brendt** [comment]
A fix ahs been released: https://github.com/spatie/async/releases/tag/1.0.3

**Comment by techno-express** [comment]
> 
> 
> A fix ahs been released: https://github.com/spatie/async/releases/tag/1.0.3

Fixed? You might need to wait to see if issue raisers, say so. No actual example of the code used to produce error submitted, and the solution has no unit test covering fix.

This should be stated as **not supported**. The fix is actually much more involved.
