### ISSUE TITLE
Call to undefined method SynchronousProcess::resolveErrorOutput() in ProcessCallbacks.php:54

### ISSUE THREAD

**Issue by ghispi** [spatie/async#79]
> PHP Fatal error:  Uncaught Error: Call to undefined method Spatie\Async\Process\SynchronousProcess::resolveErrorOutput() in vendor\spatie\async\src\Process\ProcessCallbacks.php:54

Library version: 1.0.2 & 1.0.3
Run on windows 10 via gitbash.

It seems that moving \Spatie\Async\Process\ParallelProcess::resolveErrorOutput to the \Spatie\Async\Process\ProcessCallbacks trait solves the issue but it doesnt look right cos of usage of \Spatie\Async\Output\ParallelError.

**Comment by brendt** [comment]
`SynchronousProcess` is missing its own `resolveErrorOutput` method, this should probably be added in the `Runnable` interface.

Are you open for submitting a tested PR?

PS: Do you know that this package doesn't support async on Windows? Hence you're never running tasks in parallel.

**Comment by ghispi** [comment]
> PS: Do you know that this package doesn't support async on Windows? Hence you're never running tasks in parallel.
Yes, I do. It's my dev env, pre uat on nix server. Thank you for consideration.

> Are you open for submitting a tested PR?
Sorry I am not. I'm off the town for two weeks.

**Comment by brendt** [comment]
No problem, I'll take a look at it, I'll try fix it this week.

**Comment by brendt** [comment]
Solved with #73
