### ISSUE TITLE
How to requeue a task?

### ISSUE THREAD

**Issue by valeryan** [spatie/async#80]
I am learning how to use async and I have a question for the best way to handle an exception in a task if you want to retry it. 

Basically I want to do something like this:
```
$pool = Pool::create();

foreach ($tasks as $task) {
   $pool->add(new SomeTaskThatFails($task))
   ->catch(function (Throwable $exception) {
      // deal with a problem
      // retry for success
   });
}

$pool->wait();
```

Is something like this possible? I have tried a few things but I mostly end up in an infinite loop.

**Comment by brendt** [comment]
I believe you should be able to re-add the task to the pool? 

```php
   ->catch(function (Throwable $exception) use ($pool) {
         $pool
             ->add(new SomeTaskThatFails($task))
             ->catch(function () { // Second time caught, probably do something else })
   });
```

I guess a built-in retry mechanism would be a good feature. I'm open for a PR to add this.

**Comment by valeryan** [comment]
Thanks, I'll give that a try.
