### ISSUE TITLE
Seems like lose the global context

### ISSUE THREAD

**Issue by dancespiele** [spatie/async#81]
I tried to use this lib in Laravel but I get the error `A facade root has not been set` when I use the `Storage` inside of the closure:

```php
$pool = Pool::create();

$pool[] = async(function() use ($path) {
  return Storage::disk('gcs')->exists($path);
})
->then(function($exist) use ($path) {
  if($exist) {
	Storage::disk('gcs')->delete($path);
  }
})
->catch(function($error) {
  throw new Exception($error);
});

await($pool);
```

if I don't use async it works fine.

**Comment by brendt** [comment]
That's by design. Each async task is a new PHP process. If you need complex bootstraps in your child processes, use tasks. Please refer to the README: https://github.com/spatie/async#working-with-tasks
