### ISSUE TITLE
Configurable executable

### ISSUE THREAD

**Issue by MrTschi** [spatie/async#82]
My hoster has multiple php executables installed. The „php“ command defaults to php 5.6 which wont work as the parent app runs php 7.3 because this lib spawns childs at php 5.6.
I think its this line of code:
https://github.com/spatie/async/blob/5ac27b358058d88ae74e53e590c4c89bccc6630e/src/Runtime/ParentRuntime.php#L67

How can I get it to work so the child progess also uses PHP 7.3?

**Comment by brendt** [comment]
You're right that this won't work at the moment. I'm open for a PR with tests which adds this behaviour:

```php
Pool::create()
    ->withBinary('/usr/bin/php-73')
    ->…
```

**Comment by brendt** [comment]
Fixed in 1.4.0: https://github.com/spatie/async/releases/tag/1.4.0
