### ISSUE TITLE
local.ERROR: Target [Illuminate\Contracts\Config\Repository] is not instantiable while building [Hyn\Tenancy\Database\Connection].

### ISSUE THREAD

**Issue by GaoGreen1** [spatie/async#83]
#0 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Container/Container.php(794): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Container/Container.php(927): Illuminate\Container\Container->make('Illuminate\\Cont...')
#4 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Container/Container.php(855): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Container/Container.php(816): Illuminate\Container\Container->resolveDependencies(Array)
#6 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build('Hyn\\Tenancy\\Dat...')
#7 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve('Hyn\\Tenancy\\Dat...', Array)
#8 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(121): Illuminate\Container\Container->make('Hyn\\Tenancy\\Dat...', Array)
#9 /home/shoply/public_html/api-shoply/vendor/hyn/multi-tenant/src/Traits/UsesTenantConnection.php(23): app('Hyn\\Tenancy\\Dat...')
#10 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1219): SHL\Product\Entities\Product->getConnectionName()
#11 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1051): Illuminate\Database\Eloquent\Model->getConnection()
#12 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(968): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#13 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1004): Illuminate\Database\Eloquent\Model->newModelQuery()
#14 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(957): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#15 /home/shoply/public_html/api-shoply/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(947): Illuminate\Database\Eloquent\Model->newQuery()
#16 closure://function () use ($product,$outOfStock) {
                $product = \SHL\Product\Entities\Product::query()->select('id','quantity')->where([
                    ['id',$product['pid']],
                    ['quantity','<',$product['quantity']]
                ])->first();
                if($product != null){
                    $outOfStock[]=$product->original;
                }
                return $outOfStock;
            }(3): Illuminate\Database\Eloquent\Model::query()
#17 /home/shoply/public_html/api-shoply/vendor/spatie/async/src/Runtime/ChildRuntime.php(25): Opis\Closure\SerializableClosure->{closure}()
#18 {main}

**Comment by brendt** [comment]
Please take a look at how to open a good issue: https://sebastiandedeyne.com/a-good-issue/
