### ISSUE TITLE
vendor/spatie/async/src/Runtime/ChildRuntime.php(25): Opis\Closure\SerializableClosure->{closure}()

### ISSUE THREAD

**Issue by GaoGreen1** [spatie/async#84]
In my save function, I use the pool to operate faster, but it doesn't seem to work and logs like above!
Here is my function:
public static function create(array $products, string $orderId, string $orderTotal)
    {
        $unit = null;
        $response =[];
        $pool = Pool::create();
        foreach ($products as $product) {
            $amount = $product['price'] * $product['quantity'];
            $orderTotal += $amount;
            $pool[] = async(function () use ($product, $orderId,$amount) {
                $image = null;
                $unit = $product['unit'] ?? $product['unit_name'];
                $image = $product['product']['thumbnail'] ?? $product['thumbnail'];
                $data = new  OrderProduct();
                $data->product_id = $product['pid'];
                $data->name = $product['name'];
                $data->thumbnail = $image;
                $data->order_id = $orderId;
                $data->quantity = $product['quantity'];
                $data->price = $product['price'];
                $data->unit = $unit;
                $data->total_price = $amount;
                $data->save();
                Product::remainingProduct($product['pid'], $product['quantity']);
                $output[] = $data;
                return $output;
            })->then(function (array $output) {
                return $output;
            })->catch(function (\Throwable $exception) {
                Log::error($exception->getMessage());
            });
        }
        await($pool);
        $orders = $pool->getFinished();
        foreach ($orders as $order => $value)
        {
            $response[] = $value->getOutput()[0];
        }
        $response['order_total'] = $orderTotal;
        return $response;
    }

**Comment by brendt** [comment]
This is not how this package can be used.

Please read my replies in this issue: https://github.com/spatie/async/issues/49 and this one: https://github.com/spatie/async/issues/23

Also make sure you're familiar with how PCNTL works: https://www.php.net/manual/en/intro.pcntl.php
