### ISSUE TITLE
Can't run this package on php 7.2

### ISSUE THREAD

**Issue by GaoGreen1** [spatie/async#85]
I used this package on server centos AWS . (it worked)
But not run with centos (server Vietnamese ) . and it show error 

// log error like this
closure://function () use ($product, $orderId,$amount) {
                $image = null;
                $unit = $product['unit'] ?? $product['unit_name'];
                $image = $product['product']['thumbnail'] ?? $product['thumbnail'];
                $data = new  \SHL\Order\Entities\OrderProduct();
                $data->product_id = $product['pid'];
                $data->name = $product['name'];
                $data->thumbnail = $image;
                $data->order_id = $orderId;
                $data->quantity = $product['quantity'];
                $data->price = $product['price'];
                $data->unit = $unit;
                $data->total_price = $amount;
                $data->save();
                \SHL\Product\Entities\Product::remainingProduct($product['pid'], $product['quantity']);
                $output[] = $data;
                return $output;
            }(15): Illuminate\Database\Eloquent\Model->save()
vendor/spatie/async/src/Runtime/ChildRuntime.php(25): Opis\Closure\SerializableClosure->{closure}()

**Comment by brendt** [comment]
@GaoGreen1 did you do what I suggested in #84 ?

**Comment by GaoGreen1** [comment]
yes!
