### ISSUE TITLE
is $pool->wait(); blocking?

### ISSUE THREAD

**Issue by erlangp** [spatie/async#88]

**Comment by erlangp** [comment]
```php
// ...
echo 'A';
$pool->wait();
echo 'B';
exit();
```

**Comment by brendt** [comment]
Yes, that's the point: schedule many tasks which immediately start executing, and at the end in the main thread you wait for everything to finish

**Comment by erlangp** [comment]
Oh, I see. Thank you very much for the explanation sir @brendt
