### ISSUE TITLE
Pool hangs on large output

### ISSUE THREAD

**Issue by FreezeWarp** [spatie/async#90]
I'm not sure what the exact cut-off is, though at least on outputs of several megabytes (now possible thanks to the changes in 1.1.0) on RHEL 7, the Pool seems to enter a hang state -- I don't understand the exact mechanism, but I'm guessing the output pipe is filling its buffer and then blocking for the parent process to read it, which isn't happening. Subsequently, the child process never exits, never fires SIGCHILD, and thus the Pool never completes, entering an infinite wait.

One simple solution, which may not be the best, is here: https://github.com/FreezeWarp/async/commit/deab44eef721cf1b7ac6af88fd95c4ffbf7e9351

I'm happy to open a pull request if this seems like a satisfactory solution.

Regards,
JTP

**Comment by brendt** [comment]
Seems like a good solution, though maybe we should also provide a test if possible? 

As a sidenote: if you're dealing with several megabytes of data, I think you're better off writing it to a file or a data store within your child processes. The communication line between parents and children was never meant to be used as a data bus, only for passing eg. exception data or simple output.

You see, spawning child processes already introduces overhead, so this package only shines when you're doing _lots_ of CPU or IO intensive work in _several_ child processes. If this is the case than the little overhead of writing to a datastore is negligible. On the other hand, if passing several MBs of data directly between processes is what makes the performance difference, I'd say there are better solutions than this package.

**Comment by mmartinello** [comment]
Hi,
I'm still having this problem on 1.5.3.

I'm modify my application to avoid it to print info logs on stdout and only on file, but I think you could be interested in knowing that I am able to reproduce it if we want to try some fix.

Thank you!
