### ISSUE TITLE
 InvalidArgumentException  : Unknown setter 'date'

### ISSUE THREAD

**Issue by quicklead** [spatie/async#96]
In laravel i'm has exception:

   InvalidArgumentException  : Unknown setter 'date'

  at /var/www/{PH}/data/www/{PH}/vendor/nesbot/carbon/src/Carbon/Traits/Date.php:1187
    1183|                     break;
    1184|                 }
    1185|
    1186|                 if ($this->localStrictModeEnabled ?? static::isStrictModeEnabled()) {
  > 1187|                     throw new InvalidArgumentException(sprintf("Unknown setter '%s'", $name));
    1188|                 }
    1189|
    1190|                 $this->$name = $value;
    1191|         }

  Exception trace:

  1   Carbon\Carbon::set("date", "2019-12-16 11:16:44.617064")
      /var/www/{PH}/data/www/{PH}/vendor/nesbot/carbon/src/Carbon/Traits/Date.php:1063

  2   Carbon\Carbon::__set("date", "2019-12-16 11:16:44.617064")
      [internal]:0

  Please use the argument -v to see more details.

What is this?

Code in artisan command:

$pool->add(function () use ($task, $step, $sender, $login, $password, $key, $args, $que, $chanel, $_this) {
... 
})->then( ... );

Never to use Carbon in my app, but him is give me exception on work.
If i'm disabled or removing Pool from script, him has normal work.

**Comment by brendt** [comment]
Please read https://github.com/spatie/async/issues/97

**Comment by cp-vrkansagara** [comment]
@brendt  I can understand that #97 is not resolved yet and @spatie need to contribute few example of booted framework.
