### ISSUE TITLE
Does this package need a new name, since it's not `async`, but `parallel`?

### ISSUE THREAD

**Issue by techno-express** [spatie/async#98]
I think some of the issues submitted, can be resolved by realizing it's your presentation, it pretends to be asynchronous **like**, the outcome seem asynchronous, but isn't a single thread or process.

What is your definition of **async**? What is the mechanics, the processes/steps involved? 

Your post in **Help, it doesn't work!** https://github.com/spatie/async/issues/97#issue-539026280 outline parallel execution. Maybe you should rethink **Future plans for this package** https://github.com/spatie/async/issues/4#issue-283811001

**Comment by brendt** [comment]
You're right in essence, but the package name is now so well known that we're not going to change it. Honestly I don't think changing the name would reduce the amount of issues I address with #97. People simply don't properly read the README and misunderstand what this package does, another name won't solve that.
